/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyScBoostClk.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "LCD.h"
#include "PWM1p.h"
#include "PWM2p.h"
#include "PWM1y.h"
#include "PWM2y.h"
#include "Clock_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "ADC_DelSig_1.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "QD.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "Pin_7_aliases.h"
#include "Pin_7.h"
#include "Clock_2.h"
#include "Pin_8_aliases.h"
#include "Pin_8.h"
#include "SR.h"
#include "Clock_3.h"
#include "SR2.h"
#include "SR3.h"
#include "Clock_4.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "QD_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

